use std::f32::consts::E;

use serde::{Deserialize, Serialize};
use serde_json::json;

use crate::{
    error::AppError,
    helper, logger,
    structs::{Item, ItemDetails},
    wfm_client::client::WFMClient,
};

// On New Message
// @WS/chats/NEW_MESSAGE

// Send Message
// type: "@WS/chats/SEND_MESSAGE",
// payload: {
//     chat_id: e,
//     message: t,
//     temp_id: o
// }
pub struct ChatModule<'a> {
    pub client: &'a WFMClient,
}

impl<'a> ChatModule<'a> {
    pub async fn get_chats(&self) -> Result<Vec<ChatData>, AppError> {
        match self.client.get("im/chats", Some("chats")).await {
            Ok((chats, _headers)) => Ok(chats),
            Err(e) => Err(e),
        }
    }

    pub async fn get_chat(&self, id: String) -> Result<Vec<ChatMessage>, AppError> {
        let url = format!("im/chats/{}", id);
        match self.client.get(&url, Some("messages")).await {
            Ok((chat, _headers)) => {
                logger::info(
                    "ChatModule",
                    format!("For Chat: {:?}", id).as_str(),
                    true,
                    Some(self.client.log_file.as_str()),
                );
                Ok(chat)
            }
            Err(e) => {
                let data = e.extra_data();
                println!("{:?}", data);
                Err(e)
            }
        }
    }

    pub async fn delete(&self, id: String) -> Result<String, AppError> {
        let url = format!("im/chats/{}", id);
        match self.client.delete(&url, Some("chat_id")).await {
            Ok((chat, _headers)) => {
                logger::info(
                    "ChatModule",
                    format!("Deleted Chat: {:?}", id).as_str(),
                    true,
                    Some(self.client.log_file.as_str()),
                );
                self.emit("DELETE", json!({ "id": id }));
                Ok(chat)
            }
            Err(e) => Err(e),
        }
    }
    pub fn emit(&self, operation: &str, data: serde_json::Value) {
        helper::emit_update("ChatMessages", operation, Some(data));
    }
}
/// Generated by https://quicktype.io

#[derive(Clone, Serialize, Deserialize)]
pub struct ChatData {
    #[serde(rename = "id")]
    pub id: String,

    #[serde(rename = "chat_with")]
    pub chat_with: Vec<ChatMessageWith>,

    #[serde(rename = "unread_count")]
    pub unread_count: i64,

    #[serde(rename = "chat_name")]
    pub chat_name: String,

    #[serde(rename = "messages")]
    pub messages: Vec<ChatMessage>,

    #[serde(rename = "last_update")]
    pub last_update: String,
}

#[derive(Clone, Serialize, Deserialize)]
pub struct ChatMessageWith {
    #[serde(rename = "reputation")]
    pub reputation: i64,

    #[serde(rename = "locale")]
    pub locale: String,

    #[serde(rename = "avatar")]
    pub avatar: Option<String>,

    #[serde(rename = "last_seen")]
    pub last_seen: String,

    #[serde(rename = "ingame_name")]
    pub ingame_name: String,

    #[serde(rename = "status")]
    pub status: String,

    #[serde(rename = "id")]
    pub id: String,

    #[serde(rename = "region")]
    pub region: String,
}

#[derive(Clone, Serialize, Deserialize)]
pub struct ChatMessage {
    #[serde(rename = "message")]
    pub message: String,

    #[serde(rename = "id")]
    pub id: String,

    #[serde(rename = "chat_id")]
    pub chat_id: String,

    #[serde(rename = "send_date")]
    pub send_date: String,

    #[serde(rename = "message_from")]
    pub message_from: String,

    #[serde(rename = "raw_message")]
    pub raw_message: Option<String>,
}
