//! SeaORM Entity. Generated by sea-orm-codegen 0.3.2

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

use crate::{dto::*, enums::*, trade_entry::dto::UpdateTradeEntry};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "trade_entry")]
pub struct Model {
    #[sea_orm(primary_key)]
    #[serde(skip_deserializing)]
    pub id: i64,
    pub wfm_id: String,
    pub name: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub sub_type: Option<SubType>,
    pub price: i64,
    pub group: String,
    pub tags: String,
    #[sea_orm(updated_at)]
    pub updated_at: DateTimeUtc,
    #[sea_orm(created_at)]
    pub created_at: DateTimeUtc,

    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "properties")]
    pub properties: Option<serde_json::Value>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}

impl Model {
    pub fn new(
        wfm_id: impl Into<String>,
        name: impl Into<String>,
        sub_type: Option<SubType>,
        price: i64,
        tags: Vec<impl Into<String>>,
        group: impl Into<String>,
        properties: Option<serde_json::Value>,
    ) -> Self {
        Self {
            id: Default::default(),
            wfm_id: wfm_id.into(),
            name: name.into(),
            sub_type,
            price,
            tags: tags
                .into_iter()
                .map(|tag| tag.into())
                .collect::<Vec<String>>()
                .join(","),
            group: group.into(),
            updated_at: Default::default(),
            created_at: Default::default(),
            properties,
        }
    }

    pub fn to_update(&self) -> UpdateTradeEntry {
        UpdateTradeEntry {
            id: self.id,
            price: FieldChange::Value(self.price),
            tags: FieldChange::Value(self.tags.split(',').map(|s| s.to_string()).collect()),
            sub_type: FieldChange::Value(self.sub_type.clone()),
        }
    }
}
