//! SeaORM Entity. Generated by sea-orm-codegen 0.3.2

use sea_orm::{entity::prelude::*, FromJsonQueryResult};
use serde::{Deserialize, Serialize};

use crate::dto::*;
use crate::enums::*;

#[derive(
    Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize, FromJsonQueryResult,
)]
#[sea_orm(table_name = "transaction")]
pub struct Model {
    #[sea_orm(primary_key)]
    #[serde(skip_deserializing)]
    pub id: i64,
    pub wfm_id: String,
    pub wfm_url: String,
    pub item_name: String,
    pub item_type: TransactionItemType,
    pub item_unique_name: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub sub_type: Option<SubType>,
    pub tags: String,
    pub transaction_type: TransactionType,
    pub quantity: i64,
    pub user_name: String,
    pub price: i64,
    pub profit: Option<i64>,
    #[sea_orm(updated_at)]
    pub updated_at: DateTimeUtc,
    #[sea_orm(created_at)]
    pub created_at: DateTimeUtc,
    pub properties: Option<serde_json::Value>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}

impl Model {
    pub fn new(
        wfm_id: impl Into<String>,
        wfm_url: impl Into<String>,
        item_name: impl Into<String>,
        item_type: TransactionItemType,
        item_unique_name: impl Into<String>,
        sub_type: Option<SubType>,
        tags: Vec<String>,
        transaction_type: TransactionType,
        quantity: i64,
        user_name: impl Into<String>,
        price: i64,
        properties: Option<serde_json::Value>,
    ) -> Self {
        Self {
            id: Default::default(),
            wfm_id: wfm_id.into(),
            wfm_url: wfm_url.into(),
            item_name: item_name.into(),
            item_type,
            item_unique_name: item_unique_name.into(),
            sub_type,
            tags: tags.join(","),
            transaction_type,
            quantity,
            user_name: user_name.into(),
            price,
            properties,
            profit: None,
            updated_at: Default::default(),
            created_at: Default::default(),
        }
    }
    pub fn set_profit(&mut self, profit: i64) {
        self.profit = Some(profit);
    }
}
